import "./style.css";

const content = {
  zh: {
    eyebrow: "步驟二展示",
    title: "Vite 前端整合到 Domino",
    lede:
      "這個頁面由 Vite 專案產生，並直接 build 到 Domino OSGi webapp 的 /hello-webapp/step2/。重要的是：前端內容改了，但部署機制沒有變。",
    nav: {
      home: "教程首頁",
      docs: "步驟二文件",
      step1: "步驟一步驟頁",
      step3: "步驟三展示"
    },
    checksTitle: "建置檢查",
    checks: [
      {
        label: "執行環境",
        value: "Vite build 已部署到 Domino WebContent/step2"
      },
      {
        label: "目前路徑",
        value: window.location.pathname
      },
      {
        label: "模式",
        value: "靜態前端以 OSGi webapp 方式封裝"
      },
      {
        label: "下一步",
        value: "在這個基礎上接真正的 UI 與 API"
      }
    ],
    changedTitle: "步驟二改變了什麼",
    changedBody:
      "原本手寫的 HTML、CSS、JavaScript，改成了正式的前端 build pipeline。Domino 端仍然提供同一個 /hello-webapp context root，而這一階段的內容被放在 step2 子目錄。",
    timelineTitle: "遷移順序",
    milestones: [
      {
        title: "步驟一先證明傳輸層可行",
        text: "UpdateSite NSF 與 Domino HTTP dynamic bundle 流程已經先被驗證過。"
      },
      {
        title: "步驟二替換前端實作",
        text: "Domino 的部署機制維持不變，只有 UI 內容改成由 Vite 建置。"
      },
      {
        title: "步驟三開始接 API",
        text: "當前端殼層穩定後，下一個重點就是 API origin、auth 與資料呈現。"
      }
    ]
  },
  en: {
    eyebrow: "Step 2 Showcase",
    title: "Vite Frontend on Domino",
    lede:
      "This page is generated by a Vite project and built directly into the Domino OSGi webapp bundle under /hello-webapp/step2/. The front-end implementation changed, while the deployment mechanism did not.",
    nav: {
      home: "Tutorial Home",
      docs: "Step 2 Docs",
      step1: "Step 1 Demo",
      step3: "Step 3 Demo"
    },
    checksTitle: "Build Checks",
    checks: [
      {
        label: "Runtime",
        value: "Vite build deployed inside Domino WebContent/step2"
      },
      {
        label: "Path",
        value: window.location.pathname
      },
      {
        label: "Mode",
        value: "Static frontend packaged as an OSGi webapp"
      },
      {
        label: "Next target",
        value: "Attach the real UI and API on top of this foundation"
      }
    ],
    changedTitle: "What Changed In Step 2",
    changedBody:
      "The original handwritten HTML, CSS, and JavaScript were replaced by a proper front-end build pipeline. Domino still serves the same /hello-webapp context root while this stage lives in the step2 subdirectory.",
    timelineTitle: "Migration Sequence",
    milestones: [
      {
        title: "Step 1 proved the transport layer",
        text: "The UpdateSite NSF and Domino HTTP dynamic-bundle flow were already verified first."
      },
      {
        title: "Step 2 swaps the frontend implementation",
        text: "The Domino deployment mechanism stays the same while the UI moves to a Vite build."
      },
      {
        title: "Step 3 can connect real APIs",
        text: "Once the frontend shell is stable, the next concern is API origin, auth, and data presentation."
      }
    ]
  }
};

const app = document.querySelector("#app");

function currentLang() {
  return document.body.getAttribute("data-lang") || "zh";
}

function render() {
  const lang = currentLang();
  const text = content[lang];

  app.innerHTML = `
    <div class="page-shell">
      <div class="page-topbar">
        <button type="button" class="lang-toggle" data-label-zh="English" data-label-en="中文"></button>
      </div>

      <header class="hero">
        <p class="eyebrow">${text.eyebrow}</p>
        <h1>${text.title}</h1>
        <p class="lede">${text.lede}</p>
        <nav class="hero-nav" aria-label="Step navigation">
          <a href="../index.html">${text.nav.home}</a>
          <a href="../docs/step2.html">${text.nav.docs}</a>
          <a href="../step1/index.html">${text.nav.step1}</a>
          <a href="../step3/index.html">${text.nav.step3}</a>
        </nav>
      </header>

      <main class="layout">
        <section class="panel">
          <h2>${text.checksTitle}</h2>
          <ul class="facts">
            ${text.checks
              .map(
                (item) => `
                  <li>
                    <span>${item.label}</span>
                    <strong>${item.value}</strong>
                  </li>
                `
              )
              .join("")}
          </ul>
        </section>

        <section class="panel accent-panel">
          <h2>${text.changedTitle}</h2>
          <p>${text.changedBody}</p>
        </section>

        <section class="panel timeline">
          <h2>${text.timelineTitle}</h2>
          <div class="timeline-list">
            ${text.milestones
              .map(
                (item, index) => `
                  <article class="timeline-item">
                    <p class="step-badge">0${index + 1}</p>
                    <h3>${item.title}</h3>
                    <p>${item.text}</p>
                  </article>
                `
              )
              .join("")}
          </div>
        </section>
      </main>
    </div>
  `;

  const toggle = app.querySelector(".lang-toggle");
  if (toggle) {
    toggle.textContent = lang === "zh" ? "English" : "中文";
  }
}

window.addEventListener("site-language-change", render);
render();
